library(lubridate)
data <- data.table::fread('household_power_consumption.txt')
sub_data <- subset(data, !(is.na((stringr::str_locate(string = data$Date,"2007"))[,'start'])),select = names(data))
sub_data <- subset(sub_data,dmy(sub_data$Date)== "2007-02-01"| dmy(sub_data$Date) == "2007-02-02",select = names(sub_data))
plot1 <- as.numeric(sub_data$Global_active_power) 
png("plot1.png", width=480, height=480)
hist(x =plot1,xlab = "Global Active Power(Killowatts)",main = "Global Active Power")
dev.off() 